CREATE TABLE gjj_cxgzkz (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jgbh VARCHAR2(50 CHAR),
    zjgbh VARCHAR2(50 CHAR),
    sxbh VARCHAR2(100 CHAR) NOT NULL,
    gzmc VARCHAR2(255 CHAR) NOT NULL,
    gztsy CLOB,
    sfqy VARCHAR2(10 CHAR) DEFAULT 'y',
    sfyxtqy VARCHAR2(10 CHAR) DEFAULT 'y',
    sfyxtztsy VARCHAR2(10 CHAR) DEFAULT 'n',
    role VARCHAR2(50 CHAR)
);

CREATE INDEX idx_cxgzkz_jg ON gjj_cxgzkz (jgbh, zjgbh);
CREATE INDEX idx_cxgzkz_sxbh ON gjj_cxgzkz (sxbh);

COMMENT ON TABLE gjj_cxgzkz IS '程序规则控制管理表';
COMMENT ON COLUMN gjj_cxgzkz.id IS '主键ID';
COMMENT ON COLUMN gjj_cxgzkz.jgbh IS '机构编号';
COMMENT ON COLUMN gjj_cxgzkz.zjgbh IS '子机构编号';
COMMENT ON COLUMN gjj_cxgzkz.sxbh IS '事项编号';
COMMENT ON COLUMN gjj_cxgzkz.gzmc IS '程序控制规则名称';
COMMENT ON COLUMN gjj_cxgzkz.gztsy IS '程序控制规则提示语';
COMMENT ON COLUMN gjj_cxgzkz.sfqy IS '是否启用';
COMMENT ON COLUMN gjj_cxgzkz.sfyxtqy IS '是否允许停启用';
COMMENT ON COLUMN gjj_cxgzkz.sfyxtztsy IS '是否允许调整提示语';
COMMENT ON COLUMN gjj_cxgzkz.role IS '角色';
