-- ============================================
-- 业务规则配置系统数据库初始化脚本 (Oracle版)
-- ============================================

CREATE TABLE gjj_ywnrfl (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gjsjsf VARCHAR2 (100 CHAR) NOT NULL,
    flbm VARCHAR2 (50 CHAR) NOT NULL,
    flmc VARCHAR2 (200 CHAR) NOT NULL,
    pxh NUMBER DEFAULT 0,
    sfqy NUMBER (1) DEFAULT 1,
    cjsj TIMESTAMP DEFAULT SYSTIMESTAMP,
    gxsj TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT uq_ywnrfl_code UNIQUE (gjsjsf, flbm)
);

-- 1. 业务标准库主表 (规则模板定义)
CREATE TABLE gjj_ywbzk (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pxh NUMBER DEFAULT 0, -- 排序号
    ywblbz VARCHAR2 (200 CHAR) NOT NULL, -- 业务办理标准
    tsysxmc VARCHAR2 (200 CHAR), -- 提示语属性名称
    tsysxdw VARCHAR2 (100 CHAR), -- 提示语属性单位
    zdybm VARCHAR2 (100 CHAR), -- 自定义编码
    ywbzz VARCHAR2 (100 CHAR), -- 业务标准值
    ywbzjg CLOB, -- 业务标准结果SQL
    ywblbzsm CLOB, -- 业务办理标准说明
    gjsjsf VARCHAR2 (100 CHAR), -- 关键数据算法
    ywnrfl VARCHAR2 (50 CHAR), -- 业务内容分类
    ywblfl VARCHAR2 (10 CHAR) DEFAULT '1', -- 业务办理分类: 1标准 2条件
    bzfl VARCHAR2 (50 CHAR), -- 标准分类
    cjsj TIMESTAMP DEFAULT SYSTIMESTAMP,
    gxsj TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE gjj_ywbzkhc (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mbid NUMBER NOT NULL,
    hcmbid NUMBER NOT NULL,
    cjsj TIMESTAMP DEFAULT SYSTIMESTAMP,
    gxsj TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_ywbzkhc_mbid FOREIGN KEY (mbid) REFERENCES gjj_ywbzk (id) ON DELETE CASCADE,
    CONSTRAINT fk_ywbzkhc_hcmbid FOREIGN KEY (hcmbid) REFERENCES gjj_ywbzk (id) ON DELETE CASCADE,
    CONSTRAINT uq_ywbzkhc_pair UNIQUE (mbid, hcmbid)
);

-- 2. 业务标准库属性表 (规则模板绑定的要素属性)
CREATE TABLE gjj_ywbzksx (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mbid NUMBER NOT NULL, -- 关联业务标准库的ID
    ywblbzdx VARCHAR2 (100 CHAR), -- 业务办理标准对象
    fwdxbq VARCHAR2 (100 CHAR), -- 服务对象标签 (Label)
    sxbm VARCHAR2 (50 CHAR), -- 属性编码
    ywblbzsx VARCHAR2 (100 CHAR), -- 业务办理标准属性 (如:贷款状态)
    sxly VARCHAR2 (20 CHAR), -- 属性来源 (page/sql)
    ywblbzyg CLOB, -- 业务办理标准语句 (当来源为sql时)
    cjsj TIMESTAMP DEFAULT SYSTIMESTAMP,
    gxsj TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_ywbzksx_mbid FOREIGN KEY (mbid) REFERENCES gjj_ywbzk (id) ON DELETE CASCADE
);

-- 3. 业务标准主表 (业务规则实例配置)
CREATE TABLE gjj_ywbz (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mbid NUMBER, -- 关联业务标准库的模板ID
    ywsf VARCHAR2 (50 CHAR) NOT NULL, -- 业务算法
    ywnrfl VARCHAR2 (50 CHAR), -- 业务内容分类
    gzmc VARCHAR2 (200 CHAR) NOT NULL, -- 规则名称
    gzljsm CLOB, -- 规则逻辑说明
    yxj NUMBER DEFAULT 0, -- 优先级
    sfqy NUMBER (1) DEFAULT 1, -- 是否启用 (0/1)
    cjsj TIMESTAMP DEFAULT SYSTIMESTAMP,
    gxsj TIMESTAMP DEFAULT SYSTIMESTAMP,
    jgbh VARCHAR2 (50 CHAR), -- 机构编号 (新增支持多租户)
    zjgbh VARCHAR2 (50 CHAR), -- 子机构编号
    ywbzz VARCHAR2 (100 CHAR) -- 业务标准值 (从网关获取)
);

-- 4. 业务标准属性表 (业务规则实例具体的参数/属性值)
CREATE TABLE gjj_ywbzsx (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ywid NUMBER NOT NULL, -- 关联业务标准主表的ID
    row_index NUMBER DEFAULT 0, -- 行索引(排序)
    -- 宽表字段，Oracle中如果不确定长度，可以使用 VARCHAR2(4000)
    -- 这里为了支持索引查询，建议不要用 CLOB，除非确实非常长
    k1 VARCHAR2 (1000 CHAR),
    v1 VARCHAR2 (4000 CHAR),
    k2 VARCHAR2 (1000 CHAR),
    v2 VARCHAR2 (4000 CHAR),
    k3 VARCHAR2 (1000 CHAR),
    v3 VARCHAR2 (4000 CHAR),
    k4 VARCHAR2 (1000 CHAR),
    v4 VARCHAR2 (4000 CHAR),
    k5 VARCHAR2 (1000 CHAR),
    v5 VARCHAR2 (4000 CHAR),
    k6 VARCHAR2 (1000 CHAR),
    v6 VARCHAR2 (4000 CHAR),
    k7 VARCHAR2 (1000 CHAR),
    v7 VARCHAR2 (4000 CHAR),
    k8 VARCHAR2 (1000 CHAR),
    v8 VARCHAR2 (4000 CHAR),
    k9 VARCHAR2 (1000 CHAR),
    v9 VARCHAR2 (4000 CHAR),
    k10 VARCHAR2 (1000 CHAR),
    v10 VARCHAR2 (4000 CHAR),
    result CLOB, -- 结果列
    cjsj TIMESTAMP DEFAULT SYSTIMESTAMP,
    gxsj TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_ywbzsx_ywid FOREIGN KEY (ywid) REFERENCES gjj_ywbz (id) ON DELETE CASCADE
);

CREATE TABLE gjj_ywbz_debug_case (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ywsf VARCHAR2 (50 CHAR),
    ywnrfl VARCHAR2 (50 CHAR),
    case_name VARCHAR2 (200 CHAR) NOT NULL,
    request_json CLOB NOT NULL,
    result_summary CLOB NOT NULL,
    creator_name VARCHAR2 (100 CHAR),
    jgbh VARCHAR2 (50 CHAR),
    zjgbh VARCHAR2 (50 CHAR),
    cjsj TIMESTAMP DEFAULT SYSTIMESTAMP,
    gxsj TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 5. 模型业务算法临时属性表
-- 结构按本地 Oracle 实例 `DBMS_METADATA.GET_DDL` 导出结果整理
CREATE TABLE tmp_gjj_ywblsxz (
    pcid VARCHAR2(200) DEFAULT ' ' NOT NULL, -- 批次id
    key VARCHAR2(200) DEFAULT ' ' NOT NULL, -- 属性key
    value VARCHAR2(4000) -- 属性值
);

-- 6. 业务办理标准执行日志表
-- 结构按本地 Oracle 实例 `DBMS_METADATA.GET_DDL` 导出结果整理
CREATE TABLE gjj_ywblbz_log (
    pcid VARCHAR2(200) DEFAULT ' ' NOT NULL, -- 批次id
    zxyj CLOB, -- 执行的sql语句
    cjsj TIMESTAMP(6) DEFAULT SYSTIMESTAMP, -- 插入时间
    yjlx VARCHAR2(10), -- 日志类型，1--sql语句，2--标准结果
    zxjg VARCHAR2(200) -- 执行结果
);

-- 7. 系统异常日志表
-- 结构按本地 Oracle 实例 `DBMS_METADATA.GET_DDL` 导出结果整理
CREATE TABLE t_wa_sys_log_err (
    err_date DATE,
    name_proc VARCHAR2(200),
    err_code NUMBER,
    err_msg CLOB
);

-- ============================================
-- 表及列注释
-- ============================================

COMMENT ON TABLE gjj_ywnrfl IS '业务内容分类基础表';
COMMENT ON COLUMN gjj_ywnrfl.id IS '主键ID';
COMMENT ON COLUMN gjj_ywnrfl.gjsjsf IS '关键数据算法编码';
COMMENT ON COLUMN gjj_ywnrfl.flbm IS '业务内容分类编码';
COMMENT ON COLUMN gjj_ywnrfl.flmc IS '业务内容分类名称';
COMMENT ON COLUMN gjj_ywnrfl.pxh IS '排序号';
COMMENT ON COLUMN gjj_ywnrfl.sfqy IS '是否启用';
COMMENT ON COLUMN gjj_ywnrfl.cjsj IS '创建时间';
COMMENT ON COLUMN gjj_ywnrfl.gxsj IS '更新时间';

COMMENT ON TABLE gjj_ywbzk IS '业务标准库模板主表';
COMMENT ON COLUMN gjj_ywbzk.id IS '主键ID';
COMMENT ON COLUMN gjj_ywbzk.pxh IS '排序号';
COMMENT ON COLUMN gjj_ywbzk.ywblbz IS '业务办理标准';
COMMENT ON COLUMN gjj_ywbzk.tsysxmc IS '提示语属性名称';
COMMENT ON COLUMN gjj_ywbzk.tsysxdw IS '提示语属性单位';
COMMENT ON COLUMN gjj_ywbzk.zdybm IS '自定义编码';
COMMENT ON COLUMN gjj_ywbzk.ywbzz IS '业务标准值';
COMMENT ON COLUMN gjj_ywbzk.ywbzjg IS '业务标准结果执行语句';
COMMENT ON COLUMN gjj_ywbzk.ywblbzsm IS '业务办理标准说明';
COMMENT ON COLUMN gjj_ywbzk.gjsjsf IS '关键数据算法编码';
COMMENT ON COLUMN gjj_ywbzk.ywnrfl IS '业务内容分类编码';
COMMENT ON COLUMN gjj_ywbzk.ywblfl IS '业务办理分类(1标准 2条件)';
COMMENT ON COLUMN gjj_ywbzk.bzfl IS '业务办理标准分类';
COMMENT ON COLUMN gjj_ywbzk.cjsj IS '创建时间';
COMMENT ON COLUMN gjj_ywbzk.gxsj IS '更新时间';

COMMENT ON TABLE gjj_ywbzkhc IS '业务标准互斥关系表';
COMMENT ON COLUMN gjj_ywbzkhc.id IS '主键ID';
COMMENT ON COLUMN gjj_ywbzkhc.mbid IS '当前业务标准模板ID';
COMMENT ON COLUMN gjj_ywbzkhc.hcmbid IS '互斥业务标准模板ID';
COMMENT ON COLUMN gjj_ywbzkhc.cjsj IS '创建时间';
COMMENT ON COLUMN gjj_ywbzkhc.gxsj IS '更新时间';

COMMENT ON TABLE gjj_ywbzksx IS '业务标准库属性定义表';
COMMENT ON COLUMN gjj_ywbzksx.id IS '主键ID';
COMMENT ON COLUMN gjj_ywbzksx.mbid IS '所属业务标准模板ID';
COMMENT ON COLUMN gjj_ywbzksx.ywblbzdx IS '业务办理标准属性所属对象编码';
COMMENT ON COLUMN gjj_ywbzksx.fwdxbq IS '服务对象标签';
COMMENT ON COLUMN gjj_ywbzksx.sxbm IS '属性名称/展示名称';
COMMENT ON COLUMN gjj_ywbzksx.ywblbzsx IS '属性编码/程序化标识';
COMMENT ON COLUMN gjj_ywbzksx.sxly IS '属性来源(page/sql)';
COMMENT ON COLUMN gjj_ywbzksx.ywblbzyg IS '属性来源执行语句';
COMMENT ON COLUMN gjj_ywbzksx.cjsj IS '创建时间';
COMMENT ON COLUMN gjj_ywbzksx.gxsj IS '更新时间';

COMMENT ON TABLE gjj_ywbz IS '业务规则配置主表';
COMMENT ON COLUMN gjj_ywbz.id IS '主键ID';
COMMENT ON COLUMN gjj_ywbz.mbid IS '关联业务标准模板ID';
COMMENT ON COLUMN gjj_ywbz.ywsf IS '业务算法编码';
COMMENT ON COLUMN gjj_ywbz.ywnrfl IS '业务内容分类编码';
COMMENT ON COLUMN gjj_ywbz.gzmc IS '规则名称';
COMMENT ON COLUMN gjj_ywbz.gzljsm IS '规则逻辑说明';
COMMENT ON COLUMN gjj_ywbz.yxj IS '优先级';
COMMENT ON COLUMN gjj_ywbz.sfqy IS '是否启用';
COMMENT ON COLUMN gjj_ywbz.cjsj IS '创建时间';
COMMENT ON COLUMN gjj_ywbz.gxsj IS '更新时间';
COMMENT ON COLUMN gjj_ywbz.jgbh IS '机构编号';
COMMENT ON COLUMN gjj_ywbz.zjgbh IS '子机构编号';
COMMENT ON COLUMN gjj_ywbz.ywbzz IS '业务标准值';

COMMENT ON TABLE gjj_ywbzsx IS '业务规则参数明细表';
COMMENT ON COLUMN gjj_ywbzsx.id IS '主键ID';
COMMENT ON COLUMN gjj_ywbzsx.ywid IS '所属业务规则ID';
COMMENT ON COLUMN gjj_ywbzsx.row_index IS '明细行序号';
COMMENT ON COLUMN gjj_ywbzsx.k1 IS '参数编码1';
COMMENT ON COLUMN gjj_ywbzsx.v1 IS '参数值1';
COMMENT ON COLUMN gjj_ywbzsx.k2 IS '参数编码2';
COMMENT ON COLUMN gjj_ywbzsx.v2 IS '参数值2';
COMMENT ON COLUMN gjj_ywbzsx.k3 IS '参数编码3';
COMMENT ON COLUMN gjj_ywbzsx.v3 IS '参数值3';
COMMENT ON COLUMN gjj_ywbzsx.k4 IS '参数编码4';
COMMENT ON COLUMN gjj_ywbzsx.v4 IS '参数值4';
COMMENT ON COLUMN gjj_ywbzsx.k5 IS '参数编码5';
COMMENT ON COLUMN gjj_ywbzsx.v5 IS '参数值5';
COMMENT ON COLUMN gjj_ywbzsx.k6 IS '参数编码6';
COMMENT ON COLUMN gjj_ywbzsx.v6 IS '参数值6';
COMMENT ON COLUMN gjj_ywbzsx.k7 IS '参数编码7';
COMMENT ON COLUMN gjj_ywbzsx.v7 IS '参数值7';
COMMENT ON COLUMN gjj_ywbzsx.k8 IS '参数编码8';
COMMENT ON COLUMN gjj_ywbzsx.v8 IS '参数值8';
COMMENT ON COLUMN gjj_ywbzsx.k9 IS '参数编码9';
COMMENT ON COLUMN gjj_ywbzsx.v9 IS '参数值9';
COMMENT ON COLUMN gjj_ywbzsx.k10 IS '参数编码10';
COMMENT ON COLUMN gjj_ywbzsx.v10 IS '参数值10';
COMMENT ON COLUMN gjj_ywbzsx.result IS '结果值';
COMMENT ON COLUMN gjj_ywbzsx.cjsj IS '创建时间';
COMMENT ON COLUMN gjj_ywbzsx.gxsj IS '更新时间';

COMMENT ON TABLE gjj_ywbz_debug_case IS '业务规则调试成功案例表';
COMMENT ON COLUMN gjj_ywbz_debug_case.id IS '主键ID';
COMMENT ON COLUMN gjj_ywbz_debug_case.ywsf IS '业务算法编码';
COMMENT ON COLUMN gjj_ywbz_debug_case.ywnrfl IS '业务内容分类编码';
COMMENT ON COLUMN gjj_ywbz_debug_case.case_name IS '案例名称';
COMMENT ON COLUMN gjj_ywbz_debug_case.request_json IS '调试请求报文';
COMMENT ON COLUMN gjj_ywbz_debug_case.result_summary IS '调试结果摘要';
COMMENT ON COLUMN gjj_ywbz_debug_case.creator_name IS '创建人';
COMMENT ON COLUMN gjj_ywbz_debug_case.jgbh IS '机构编号';
COMMENT ON COLUMN gjj_ywbz_debug_case.zjgbh IS '子机构编号';
COMMENT ON COLUMN gjj_ywbz_debug_case.cjsj IS '创建时间';
COMMENT ON COLUMN gjj_ywbz_debug_case.gxsj IS '更新时间';

-- ============================================
-- 创建索引
-- ============================================

-- 库表索引
CREATE INDEX idx_gjj_ywbzk_pxh ON gjj_ywbzk (pxh);
CREATE UNIQUE INDEX idx_gjj_ywbzk_zdybm ON gjj_ywbzk (zdybm);
CREATE INDEX idx_gjj_ywbzkhc_mbid ON gjj_ywbzkhc (mbid);
CREATE INDEX idx_gjj_ywnrfl_sf ON gjj_ywnrfl (gjsjsf, sfqy);
-- CREATE INDEX idx_gjj_ywbzk_sf ON gjj_ywbzk (ywsf); -- ywsf not in table

-- 库属性表索引
CREATE INDEX idx_gjj_ywbzksx_mb ON gjj_ywbzksx (mbid);

-- 业务配置表索引
CREATE INDEX idx_gjj_ywbz_mb ON gjj_ywbz (mbid);

CREATE INDEX idx_gjj_ywbz_yxj ON gjj_ywbz (yxj);

CREATE INDEX idx_gjj_ywbz_jg ON gjj_ywbz (jgbh, zjgbh);

-- 业务属性表索引
CREATE INDEX idx_gjj_ywbzsx_yw ON gjj_ywbzsx (ywid);

CREATE INDEX idx_gjj_ywbzsx_k1 ON gjj_ywbzsx (k1);
CREATE INDEX idx_gjj_ywbz_debug_case_scope ON gjj_ywbz_debug_case (jgbh, zjgbh, ywsf, ywnrfl);
