-- ============================================
-- 业务标准升级投产脚本（GaussDB）
-- 适用改造点：1-5、8-10
-- 对应文档：docs/业务标准升级方案.md
-- ============================================
--
-- 执行前建议：
-- 1. 先完整备份目标库。
-- 2. 确认旧库已存在基础表：public.gjj_ywbzk / public.gjj_ywbz / public.gjj_ywbzksx / public.gjj_ywbzsx。
-- 3. 若 public.gjj_ywbzk.zdybm 已存在重复非空值，唯一索引会创建失败，请先清理后执行。
--
-- 说明：
-- - 改造点 1 仅涉及本地 JSON 配置，不涉及数据库 DDL。
-- - 本脚本基于 PostgreSQL/GaussDB 兼容语法编写，支持重复执行。

-- [改造点 2] 业务内容分类表 gjj_ywnrfl
CREATE TABLE IF NOT EXISTS public.gjj_ywnrfl (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gjsjsf CHARACTER VARYING(100) NOT NULL,
    flbm CHARACTER VARYING(50) NOT NULL,
    flmc CHARACTER VARYING(200) NOT NULL,
    pxh NUMERIC DEFAULT 0,
    sfqy NUMERIC(1, 0) DEFAULT 1,
    cjsj TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    gxsj TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_gjj_ywnrfl_code UNIQUE (gjsjsf, flbm)
);

CREATE INDEX IF NOT EXISTS idx_gjj_ywnrfl_sf
    ON public.gjj_ywnrfl (gjsjsf, sfqy);

-- [改造点 3] gjj_ywbzk 新增 zdybm
ALTER TABLE public.gjj_ywbzk
    ADD COLUMN IF NOT EXISTS zdybm CHARACTER VARYING(100);

CREATE UNIQUE INDEX IF NOT EXISTS idx_gjj_ywbzk_zdybm
    ON public.gjj_ywbzk (zdybm);

-- [改造点 4] gjj_ywbzk 新增 ywblfl，并补默认值
ALTER TABLE public.gjj_ywbzk
    ADD COLUMN IF NOT EXISTS ywblfl CHARACTER VARYING(10) DEFAULT '1';

UPDATE public.gjj_ywbzk
   SET ywblfl = '1'
 WHERE ywblfl IS NULL;

-- [改造点 10] gjj_ywbzk 新增提示语属性字段
ALTER TABLE public.gjj_ywbzk
    ADD COLUMN IF NOT EXISTS tsysxmc CHARACTER VARYING(200);

ALTER TABLE public.gjj_ywbzk
    ADD COLUMN IF NOT EXISTS tsysxdw CHARACTER VARYING(100);

-- [改造点 5] 互斥关系表 gjj_ywbzkhc
CREATE TABLE IF NOT EXISTS public.gjj_ywbzkhc (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mbid BIGINT NOT NULL REFERENCES public.gjj_ywbzk(id) ON DELETE CASCADE,
    hcmbid BIGINT NOT NULL REFERENCES public.gjj_ywbzk(id) ON DELETE CASCADE,
    cjsj TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    gxsj TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_gjj_ywbzkhc_pair UNIQUE (mbid, hcmbid)
);

CREATE INDEX IF NOT EXISTS idx_gjj_ywbzkhc_mbid
    ON public.gjj_ywbzkhc (mbid);

-- [改造点 8] gjj_ywbz 新增 ywbzz
ALTER TABLE public.gjj_ywbz
    ADD COLUMN IF NOT EXISTS ywbzz CHARACTER VARYING(100);

-- [改造点 9] 调试成功案例表 gjj_ywbz_debug_case
CREATE TABLE IF NOT EXISTS public.gjj_ywbz_debug_case (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ywsf CHARACTER VARYING(50),
    ywnrfl CHARACTER VARYING(50),
    case_name CHARACTER VARYING(200) NOT NULL,
    request_json TEXT NOT NULL,
    result_summary TEXT NOT NULL,
    creator_name CHARACTER VARYING(100),
    jgbh CHARACTER VARYING(50),
    zjgbh CHARACTER VARYING(50),
    cjsj TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    gxsj TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_gjj_ywbz_debug_case_scope
    ON public.gjj_ywbz_debug_case (jgbh, zjgbh, ywsf, ywnrfl);

-- 可选校验：
-- SELECT table_name
--   FROM information_schema.tables
--  WHERE table_schema = 'public'
--    AND table_name IN ('gjj_ywnrfl', 'gjj_ywbzkhc', 'gjj_ywbz_debug_case');
--
-- SELECT column_name
--   FROM information_schema.columns
--  WHERE table_schema = 'public'
--    AND table_name = 'gjj_ywbzk'
--    AND column_name IN ('zdybm', 'ywblfl', 'tsysxmc', 'tsysxdw');
--
-- SELECT column_name
--   FROM information_schema.columns
--  WHERE table_schema = 'public'
--    AND table_name = 'gjj_ywbz'
--    AND column_name = 'ywbzz';
