-- ============================================
-- 业务标准升级投产脚本（人大金仓）
-- 适用改造点：1-5、8-10、14
-- 对应文档：docs/业务标准升级方案.md
-- ============================================
--
-- 执行前建议：
-- 1. 先完整备份目标库。
-- 2. 确认旧库已存在基础表：public.gjj_ywbzk / public.gjj_ywbz / public.gjj_ywbzksx / public.gjj_ywbzsx。
-- 3. 若 public.gjj_ywbzk.zdybm 已存在重复非空值，唯一索引会创建失败，请先清理后执行。
--
-- 说明：
-- - 改造点 1 仅涉及本地 JSON 配置，不涉及数据库 DDL。
-- - 本脚本基于 PostgreSQL/人大金仓兼容语法，支持重复执行。

-- [改造点 2] 业务内容分类表 gjj_ywnrfl
CREATE TABLE IF NOT EXISTS public.gjj_ywnrfl (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gjsjsf CHARACTER VARYING(100) NOT NULL,
    flbm CHARACTER VARYING(50) NOT NULL,
    flmc CHARACTER VARYING(200) NOT NULL,
    quanzhong NUMERIC(5, 0),
    pxh NUMERIC DEFAULT 0,
    sfqy NUMERIC(1, 0) DEFAULT 1,
    cjsj TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    gxsj TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_gjj_ywnrfl_code UNIQUE (gjsjsf, flbm)
);

CREATE INDEX IF NOT EXISTS idx_gjj_ywnrfl_sf
    ON public.gjj_ywnrfl (gjsjsf, sfqy);

ALTER TABLE public.gjj_ywnrfl
    ADD COLUMN IF NOT EXISTS quanzhong NUMERIC(5, 0);

-- [改造点 3] gjj_ywbzk 新增 zdybm
ALTER TABLE public.gjj_ywbzk
    ADD COLUMN IF NOT EXISTS zdybm CHARACTER VARYING(100);

CREATE UNIQUE INDEX IF NOT EXISTS idx_gjj_ywbzk_zdybm
    ON public.gjj_ywbzk (zdybm);

-- [改造点 4] gjj_ywbzk 新增 ywblfl，并补默认值
ALTER TABLE public.gjj_ywbzk
    ADD COLUMN IF NOT EXISTS ywblfl CHARACTER VARYING(10) DEFAULT '1';

UPDATE public.gjj_ywbzk
   SET ywblfl = '1'
 WHERE ywblfl IS NULL;

ALTER TABLE public.gjj_ywbzk
    ADD COLUMN IF NOT EXISTS fenzhi NUMERIC(5, 0);

-- [改造点 10] gjj_ywbzk 新增提示语属性字段
ALTER TABLE public.gjj_ywbzk
    ADD COLUMN IF NOT EXISTS tsysxmc CHARACTER VARYING(200);

ALTER TABLE public.gjj_ywbzk
    ADD COLUMN IF NOT EXISTS tsysxdw CHARACTER VARYING(100);

-- [改造点 5] 互斥关系表 gjj_ywbzkhc
CREATE TABLE IF NOT EXISTS public.gjj_ywbzkhc (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mbid BIGINT NOT NULL REFERENCES public.gjj_ywbzk(id) ON DELETE CASCADE,
    hcmbid BIGINT NOT NULL REFERENCES public.gjj_ywbzk(id) ON DELETE CASCADE,
    cjsj TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    gxsj TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_gjj_ywbzkhc_pair UNIQUE (mbid, hcmbid)
);

CREATE INDEX IF NOT EXISTS idx_gjj_ywbzkhc_mbid
    ON public.gjj_ywbzkhc (mbid);

-- [改造点 8] gjj_ywbz 新增 ywbzz
ALTER TABLE public.gjj_ywbz
    ADD COLUMN IF NOT EXISTS ywbzz CHARACTER VARYING(100);

-- [改造点 9] 调试成功案例表 gjj_ywbz_debug_case
CREATE TABLE IF NOT EXISTS public.gjj_ywbz_debug_case (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ywsf CHARACTER VARYING(50),
    ywnrfl CHARACTER VARYING(50),
    case_name CHARACTER VARYING(200) NOT NULL,
    request_json TEXT NOT NULL,
    result_summary TEXT NOT NULL,
    creator_name CHARACTER VARYING(100),
    jgbh CHARACTER VARYING(50),
    zjgbh CHARACTER VARYING(50),
    cjsj TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    gxsj TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_gjj_ywbz_debug_case_scope
    ON public.gjj_ywbz_debug_case (jgbh, zjgbh, ywsf, ywnrfl);

COMMENT ON TABLE public.gjj_ywnrfl IS '业务内容分类基础表';
COMMENT ON COLUMN public.gjj_ywnrfl.id IS '主键ID';
COMMENT ON COLUMN public.gjj_ywnrfl.gjsjsf IS '关键数据算法编码';
COMMENT ON COLUMN public.gjj_ywnrfl.flbm IS '业务内容分类编码';
COMMENT ON COLUMN public.gjj_ywnrfl.flmc IS '业务内容分类名称';
COMMENT ON COLUMN public.gjj_ywnrfl.quanzhong IS '权重值';
COMMENT ON COLUMN public.gjj_ywnrfl.pxh IS '排序号';
COMMENT ON COLUMN public.gjj_ywnrfl.sfqy IS '是否启用';
COMMENT ON COLUMN public.gjj_ywnrfl.cjsj IS '创建时间';
COMMENT ON COLUMN public.gjj_ywnrfl.gxsj IS '更新时间';

COMMENT ON TABLE public.gjj_ywbzk IS '业务标准库模板主表';
COMMENT ON COLUMN public.gjj_ywbzk.id IS '主键ID';
COMMENT ON COLUMN public.gjj_ywbzk.pxh IS '排序号';
COMMENT ON COLUMN public.gjj_ywbzk.ywblbz IS '业务办理标准';
COMMENT ON COLUMN public.gjj_ywbzk.tsysxmc IS '提示语属性名称';
COMMENT ON COLUMN public.gjj_ywbzk.tsysxdw IS '提示语属性单位';
COMMENT ON COLUMN public.gjj_ywbzk.zdybm IS '自定义编码';
COMMENT ON COLUMN public.gjj_ywbzk.ywbzz IS '业务标准值';
COMMENT ON COLUMN public.gjj_ywbzk.ywbzjg IS '业务标准结果执行语句';
COMMENT ON COLUMN public.gjj_ywbzk.fenzhi IS '风险分值';
COMMENT ON COLUMN public.gjj_ywbzk.ywblbzsm IS '业务办理标准说明';
COMMENT ON COLUMN public.gjj_ywbzk.gjsjsf IS '关键数据算法编码';
COMMENT ON COLUMN public.gjj_ywbzk.ywnrfl IS '业务内容分类编码';
COMMENT ON COLUMN public.gjj_ywbzk.ywblfl IS '业务办理分类(1标准 2条件 3风险)';
COMMENT ON COLUMN public.gjj_ywbzk.bzfl IS '业务办理标准分类';
COMMENT ON COLUMN public.gjj_ywbzk.cjsj IS '创建时间';
COMMENT ON COLUMN public.gjj_ywbzk.gxsj IS '更新时间';

COMMENT ON TABLE public.gjj_ywbzkhc IS '业务标准互斥关系表';
COMMENT ON COLUMN public.gjj_ywbzkhc.id IS '主键ID';
COMMENT ON COLUMN public.gjj_ywbzkhc.mbid IS '当前业务标准模板ID';
COMMENT ON COLUMN public.gjj_ywbzkhc.hcmbid IS '互斥业务标准模板ID';
COMMENT ON COLUMN public.gjj_ywbzkhc.cjsj IS '创建时间';
COMMENT ON COLUMN public.gjj_ywbzkhc.gxsj IS '更新时间';

COMMENT ON TABLE public.gjj_ywbzksx IS '业务标准库属性定义表';
COMMENT ON COLUMN public.gjj_ywbzksx.id IS '主键ID';
COMMENT ON COLUMN public.gjj_ywbzksx.mbid IS '所属业务标准模板ID';
COMMENT ON COLUMN public.gjj_ywbzksx.ywblbzdx IS '业务办理标准属性所属对象编码';
COMMENT ON COLUMN public.gjj_ywbzksx.fwdxbq IS '服务对象标签';
COMMENT ON COLUMN public.gjj_ywbzksx.sxbm IS '属性名称/展示名称';
COMMENT ON COLUMN public.gjj_ywbzksx.ywblbzsx IS '属性编码/程序化标识';
COMMENT ON COLUMN public.gjj_ywbzksx.sxly IS '属性来源(page/sql)';
COMMENT ON COLUMN public.gjj_ywbzksx.ywblbzyg IS '属性来源执行语句';
COMMENT ON COLUMN public.gjj_ywbzksx.cjsj IS '创建时间';
COMMENT ON COLUMN public.gjj_ywbzksx.gxsj IS '更新时间';

COMMENT ON TABLE public.gjj_ywbz IS '业务规则配置主表';
COMMENT ON COLUMN public.gjj_ywbz.id IS '主键ID';
COMMENT ON COLUMN public.gjj_ywbz.mbid IS '关联业务标准模板ID';
COMMENT ON COLUMN public.gjj_ywbz.ywsf IS '业务算法编码';
COMMENT ON COLUMN public.gjj_ywbz.ywnrfl IS '业务内容分类编码';
COMMENT ON COLUMN public.gjj_ywbz.gzmc IS '规则名称';
COMMENT ON COLUMN public.gjj_ywbz.gzljsm IS '规则逻辑说明';
COMMENT ON COLUMN public.gjj_ywbz.yxj IS '优先级';
COMMENT ON COLUMN public.gjj_ywbz.sfqy IS '是否启用';
COMMENT ON COLUMN public.gjj_ywbz.cjsj IS '创建时间';
COMMENT ON COLUMN public.gjj_ywbz.gxsj IS '更新时间';
COMMENT ON COLUMN public.gjj_ywbz.jgbh IS '机构编号';
COMMENT ON COLUMN public.gjj_ywbz.zjgbh IS '子机构编号';
COMMENT ON COLUMN public.gjj_ywbz.ywbzz IS '业务标准值';

COMMENT ON TABLE public.gjj_ywbzsx IS '业务规则参数明细表';
COMMENT ON COLUMN public.gjj_ywbzsx.id IS '主键ID';
COMMENT ON COLUMN public.gjj_ywbzsx.ywid IS '所属业务规则ID';
COMMENT ON COLUMN public.gjj_ywbzsx.row_index IS '明细行序号';
COMMENT ON COLUMN public.gjj_ywbzsx.k1 IS '参数编码1';
COMMENT ON COLUMN public.gjj_ywbzsx.v1 IS '参数值1';
COMMENT ON COLUMN public.gjj_ywbzsx.k2 IS '参数编码2';
COMMENT ON COLUMN public.gjj_ywbzsx.v2 IS '参数值2';
COMMENT ON COLUMN public.gjj_ywbzsx.k3 IS '参数编码3';
COMMENT ON COLUMN public.gjj_ywbzsx.v3 IS '参数值3';
COMMENT ON COLUMN public.gjj_ywbzsx.k4 IS '参数编码4';
COMMENT ON COLUMN public.gjj_ywbzsx.v4 IS '参数值4';
COMMENT ON COLUMN public.gjj_ywbzsx.k5 IS '参数编码5';
COMMENT ON COLUMN public.gjj_ywbzsx.v5 IS '参数值5';
COMMENT ON COLUMN public.gjj_ywbzsx.k6 IS '参数编码6';
COMMENT ON COLUMN public.gjj_ywbzsx.v6 IS '参数值6';
COMMENT ON COLUMN public.gjj_ywbzsx.k7 IS '参数编码7';
COMMENT ON COLUMN public.gjj_ywbzsx.v7 IS '参数值7';
COMMENT ON COLUMN public.gjj_ywbzsx.k8 IS '参数编码8';
COMMENT ON COLUMN public.gjj_ywbzsx.v8 IS '参数值8';
COMMENT ON COLUMN public.gjj_ywbzsx.k9 IS '参数编码9';
COMMENT ON COLUMN public.gjj_ywbzsx.v9 IS '参数值9';
COMMENT ON COLUMN public.gjj_ywbzsx.k10 IS '参数编码10';
COMMENT ON COLUMN public.gjj_ywbzsx.v10 IS '参数值10';
COMMENT ON COLUMN public.gjj_ywbzsx.result IS '结果值';
COMMENT ON COLUMN public.gjj_ywbzsx.cjsj IS '创建时间';
COMMENT ON COLUMN public.gjj_ywbzsx.gxsj IS '更新时间';

COMMENT ON TABLE public.gjj_ywbz_debug_case IS '业务规则调试成功案例表';
COMMENT ON COLUMN public.gjj_ywbz_debug_case.id IS '主键ID';
COMMENT ON COLUMN public.gjj_ywbz_debug_case.ywsf IS '业务算法编码';
COMMENT ON COLUMN public.gjj_ywbz_debug_case.ywnrfl IS '业务内容分类编码';
COMMENT ON COLUMN public.gjj_ywbz_debug_case.case_name IS '案例名称';
COMMENT ON COLUMN public.gjj_ywbz_debug_case.request_json IS '调试请求报文';
COMMENT ON COLUMN public.gjj_ywbz_debug_case.result_summary IS '调试结果摘要';
COMMENT ON COLUMN public.gjj_ywbz_debug_case.creator_name IS '创建人';
COMMENT ON COLUMN public.gjj_ywbz_debug_case.jgbh IS '机构编号';
COMMENT ON COLUMN public.gjj_ywbz_debug_case.zjgbh IS '子机构编号';
COMMENT ON COLUMN public.gjj_ywbz_debug_case.cjsj IS '创建时间';
COMMENT ON COLUMN public.gjj_ywbz_debug_case.gxsj IS '更新时间';

-- [同步 ID 20 业务内容分类]
INSERT INTO gjj_ywnrfl (gjsjsf, flbm, flmc, quanzhong, pxh, sfqy, cjsj, gxsj)
SELECT '20', flbm, flmc, quanzhong, pxh, sfqy, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM gjj_ywnrfl
WHERE gjsjsf = '1'
ON CONFLICT (gjsjsf, flbm) DO NOTHING;
