-- =========================================
-- SQLite 建表语句
-- =========================================
CREATE TABLE IF NOT EXISTS gjj_cxgzkz (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    jgbh VARCHAR(50),
    zjgbh VARCHAR(50),
    sxbh VARCHAR(100) NOT NULL,
    gzmc VARCHAR(255) NOT NULL,
    gztsy VARCHAR(1000),
    sfqy VARCHAR(10) DEFAULT 'y',
    sfyxtqy VARCHAR(10) DEFAULT 'y',
    sfyxtztsy VARCHAR(10) DEFAULT 'n',
    role VARCHAR(50)
);

-- =========================================
-- Oracle 建表语句 (请在 Oracle 客户端中执行)
-- =========================================
/*
CREATE TABLE gjj_cxgzkz (
id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
jgbh VARCHAR2(50),
zjgbh VARCHAR2(50),
sxbh VARCHAR2(100) NOT NULL,
gzmc VARCHAR2(255) NOT NULL,
gztsy VARCHAR2(1000),
sfqy VARCHAR2(10) DEFAULT 'y',
sfyxtqy VARCHAR2(10) DEFAULT 'y',
sfyxtztsy VARCHAR2(10) DEFAULT 'n',
role VARCHAR2(50)
);

COMMENT ON TABLE gjj_cxgzkz IS '程序控制规则管理表';
COMMENT ON COLUMN gjj_cxgzkz.id IS '主键ID';
COMMENT ON COLUMN gjj_cxgzkz.jgbh IS '机构编号';
COMMENT ON COLUMN gjj_cxgzkz.zjgbh IS '子机构编号';
COMMENT ON COLUMN gjj_cxgzkz.sxbh IS '事项编号';
COMMENT ON COLUMN gjj_cxgzkz.gzmc IS '规则名称';
COMMENT ON COLUMN gjj_cxgzkz.gztsy IS '规则提示语';
COMMENT ON COLUMN gjj_cxgzkz.sfqy IS '是否启用 (y/n)';
COMMENT ON COLUMN gjj_cxgzkz.sfyxtqy IS '是否允许停启用 (y/n)';
COMMENT ON COLUMN gjj_cxgzkz.sfyxtztsy IS '是否允许调整提示语 (y/n)';
COMMENT ON COLUMN gjj_cxgzkz.role IS '角色';
*/
